"""Independent-simulator check: Icarus Verilog on every emitted puzzle Verilog.

  python tests\\test_iverilog.py

Compiles each Verilog artifact the tool emits for the puzzle -

  03_netlist.v + cells_sim.v   structural netlist + generated cell models
  04_behavioral.v              de-synthesised RTL
  07_rtl_lifted.v              full lifted RTL

- drives the winning input through a common testbench under Icarus Verilog (an
independent, industry-standard simulator - not our Python), and requires `success`
to rise and `O` to spell the winning message in all three.

Opt-in like the Caravel suite: if no iverilog executable is found the suite reports
SKIP and exits 0.  Icarus setup notes are in results/roundtrip/run_iverilog.ps1.
"""
import json
import os
import shutil
import subprocess
import sys

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TESTS_DIR)
from testutil import Checks
from gds2v import paths

WIN = "(* TWO STARS *)"
CONDA_VERI = r"C:\Users\ramku\.conda\envs\veri\Library\bin"

TB = r"""// generated by tests/test_iverilog.py - common testbench for every emitted RTL
`timescale 1ns / 1ps
module tb;
    reg clk = 0, rst_n = 0, enable = 0, I = 0;
    wire [7:0] O;
    wire success;
    puzzle dut (.O(O), .I(I), .clk(clk), .enable(enable), .rst_n(rst_n),
                .success(success));
    always #5 clk = ~clk;
    localparam [120:0] ANS = 121'b%BITS%;
    integer k, mi = 0;
    reg seen = 0;
    reg [8*20-1:0] msg = 0;
    initial begin
        rst_n = 0; enable = 0; I = 0;
        repeat (3) @(posedge clk);
        rst_n = 1;
        @(negedge clk);
        enable = 1;
        for (k = 0; k < 121; k = k + 1) begin
            I = ANS[120 - k];
            @(negedge clk);
        end
        enable = 0; I = 0;
        for (k = 0; k < 40; k = k + 1) begin
            @(posedge clk);
            if (success === 1'b1) seen = 1;
            if (O !== 8'd0 && mi < 20) begin
                msg[8*mi +: 8] = O;
                mi = mi + 1;
            end
        end
        $write("success=%0d message=[", seen);
        for (k = 0; k < mi; k = k + 1) $write("%c", msg[8*k +: 8]);
        $display("]");
        $finish;
    end
endmodule
"""


def find_iverilog():
    exe = shutil.which("iverilog")
    if exe:
        return os.path.dirname(exe)
    if os.path.exists(os.path.join(CONDA_VERI, "iverilog.exe")):
        return CONDA_VERI
    return None


def main():
    bindir = find_iverilog()
    if bindir is None:
        print("SKIP: no iverilog executable found "
              "(see results/roundtrip/run_iverilog.ps1 for setup)")
        return 0
    c = Checks()
    out = paths.PUZZLE_OUT
    bits = json.load(open(out / "solution.json"))["bits"]
    tb = str(out / "tb_iverilog.v")
    open(tb, "w").write(TB.replace("%BITS%", bits))

    variants = (
        ("03_netlist.v + cells_sim.v",
         [str(out / "03_netlist.v"), str(out / "cells_sim.v")]),
        ("04_behavioral.v", [str(out / "04_behavioral.v")]),
        ("07_rtl_lifted.v", [str(out / "07_rtl_lifted.v")]),
    )
    for label, files in variants:
        vvp = str(out / "tb_iverilog.vvp")
        r = subprocess.run([os.path.join(bindir, "iverilog"), "-g2012", "-o", vvp,
                            tb] + files, capture_output=True, text=True)
        if r.returncode != 0:
            c.check(f"iverilog: {label} compiles", False,
                    (r.stdout + r.stderr).strip()[:100])
            continue
        r = subprocess.run([os.path.join(bindir, "vvp"), vvp],
                           capture_output=True, text=True)
        text = r.stdout + r.stderr
        good = r.returncode == 0 and f"success=1 message=[{WIN}]" in text
        c.check(f"iverilog: {label} raises success and prints {WIN!r}", good,
                text.strip().splitlines()[-1][:80] if text.strip() else "no output")
    return 0 if c.summary() else 1


if __name__ == "__main__":
    sys.exit(main())
